### ISSUE TITLE
Upgrade apache-rat-plugin so it can be disabled.

### ISSUE THREAD

**Issue by deragon** [streamsets/datacollector-api#1]
Current apache-rat-plugin 0.8 does not seam to permit skipping rat testing.  As an occasional open source contributor, I simply wanted to build quickly datacollector-api without all the configuration hassle of rat.  I tried:

`mvn -DskipTests -DskipRat -Drat.skip=true -Drat.ignoreErrors=true install`

...but apache-rat-plugin 0.8 would still attempt to perform its job and fail.  Upgrading to apache-rat-plugin 0.12 permitted me to run:

`mvn -DskipTests -Drat.skip=true install`

This successfully built and installed datacollector-api.

**Comment by kunickiaj** [comment]
This sounds like a good idea to me.

**Comment by kunickiaj** [comment]
https://issues.streamsets.com/browse/SDC-3294

Just realized this is for datacollector-api. All issues should be filed at https://issues.streamsets.com and not on Github.
